"""empty message

Revision ID: 45ed13253c19
Revises: 9e04d063d603
Create Date: 2024-07-24 00:02:15.408446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45ed13253c19'
down_revision = '9e04d063d603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('niche', sa.String(length=100), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('followers', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('platform', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('platform')
        batch_op.drop_column('followers')

    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.drop_column('niche')

    # ### end Alembic commands ###
