"""Added flagged boolean

Revision ID: 9e04d063d603
Revises: d523cdd6cc3f
Create Date: 2024-06-29 19:30:34.922259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e04d063d603'
down_revision = 'd523cdd6cc3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flagged', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flagged', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('flagged')

    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.drop_column('flagged')

    # ### end Alembic commands ###
